name: check
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.0
  animated_splash_screen: ^1.3.0
  curved_navigation_bar: ^1.0.3
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  get: ^4.6.6
  video_player: ^2.8.3
  chewie: ^1.0.0
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  firebase_messaging: ^14.7.19
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1
  lottie: ^3.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:

  uses-material-design: true
  assets:
    - assets/images/hello.png
    - assets/images/photo4.gif
    - assets/images/photo1.png
    - assets/images/photo3.gif
    - assets/alphabet/A.jpg
    - assets/alphabet/B.jpg
    - assets/alphabet/C.jpg
    - assets/alphabet/D.jpg
    - assets/alphabet/E.jpg
    - assets/alphabet/F.jpg
    - assets/alphabet/G.jpg
    - assets/alphabet/H.jpg
    - assets/alphabet/I.jpg
    - assets/alphabet/J.gif
    - assets/alphabet/K.jpg
    - assets/alphabet/L.jpg
    - assets/alphabet/M.jpg
    - assets/alphabet/N.jpg
    - assets/alphabet/O.jpg
    - assets/alphabet/P.jpg
    - assets/alphabet/Q.jpg
    - assets/alphabet/R.jpg
    - assets/alphabet/S.jpg
    - assets/alphabet/T.jpg
    - assets/alphabet/U.jpg
    - assets/alphabet/V.jpg
    - assets/alphabet/W.jpg
    - assets/alphabet/X.jpg
    - assets/alphabet/Y.jpg
    - assets/alphabet/Z.gif
    - assets/color/black.gif
    - assets/color/blue.gif
    - assets/color/green.gif
    - assets/color/orange.gif
    - assets/color/red.gif
    - assets/color/white.gif
    - assets/color/yellow.gif
    - assets/expression/angry.gif
    - assets/expression/bored.gif
    - assets/expression/excited.gif
    - assets/expression/happy.gif
    - assets/expression/nervous.gif
    - assets/expression/sad.gif
    - assets/greeting/after.gif
    - assets/greeting/goodbye.gif
    - assets/greeting/hello.gif
    - assets/greeting/morning.gif
    - assets/greeting/night.gif
    - assets/greeting/seeyoulater.gif
    - assets/number/1.png
    - assets/number/2.png
    - assets/number/3.png
    - assets/number/4.png
    - assets/number/5.png
    - assets/number/6.png
    - assets/number/7.png
    - assets/number/8.png
    - assets/number/9.png
    - assets/number/10.gif
